version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - network
    restart: unless-stopped

  frontend:
    build: ./mindbridge
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    driver: bridge