version: "3.8"

services:
  backend:
    image: petersonguo/backend:latest  # Use the backend image from Docker Hub
    env_file:
      - ./backend/.env
    networks:
      - network
    restart: unless-stopped

  frontend:
    image: petersonguo/mindbridge:latest  # Use the frontend image from Docker Hub
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    driver: bridge
