# Use a more recent and supported version of Node.js
FROM --platform=linux/amd64 node:lts-alpine3.19

# Set the working directory in the container
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH for easier script execution
ENV PATH /app/node_modules/.bin:$PATH

# Install app dependencies
COPY package.json ./
RUN npm install --silent

# Expose port 3000 to access the server
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]