name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./mindbridge/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_IP }}
        username: root
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          docker-compose down
          docker-compose up -d
          # Update your docker-compose.yml to use the images from Docker Hub
